### ISSUE TITLE
Fjern .pgpass fra repositoriet

### ISSUE THREAD

**Issue by ninsbl** [NINAnor/IBECA#6]
Den har kanskje sneket seg inn med en `git add *`:
https://github.com/NINAnor/IBECA/blob/0621cf29a9e61847d054e1bbfe3764ccb6291148/R/.pgpass#L1

**Comment by frafra** [comment]
Eller med `git add . ` (`.pgpass` er ikke i `.gitignore`).

**Comment by anders-kolstad** [comment]
Ja, jeg var litt rask i vendingene. Den skal være slettet nå.

**Comment by anders-kolstad** [comment]
Men jeg ser den fortsatt ligger i 'history' - er det noen som vet hvordan jeg sletter alle spor? @ninsbl @frafra

**Comment by ninsbl** [comment]
Det ligger kanskje noen tips her: 
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

Det er ikke så farlig for denne databasen er a) bak brannmuren og b) har postgjest svært begrensete rettigheter ...

**Comment by frafra** [comment]
Denne databasebruker vil endre seg i løpet av de neste månedene.
Endring av git-historikk kan forårsake problemer for andre brukere hvis de ikke er kjent med git.
